### PR TITLE
Fix ValidationError causing HTTP/500 in Python 2.x

### LINKED ISSUE #122: ValidationError causes HTTP/500 in Flask instead of HTTP/422 in Python 2
Here are the symptoms: http://stackoverflow.com/questions/37321835/flask-error-handler-not-able-to-handle-assertion-error/39624893#39624893

Here is the case where I personally hit the issue with Python 2.x and PyPy in Python 2.x mode only: https://travis-ci.org/frol/flask-restplus-server-example/builds/161685419

After troubleshooting, I discovered that this issue stems from the `FlaskParser.handle_error` which calls `abort` function with `exc=` argument, which then [is set as "data"](https://github.com/sloria/webargs/blob/dev/webargs/flaskparser.py#L38) on the raised `HTTPException`, which in its turn is tried to be json-dumped and fails with `TypeError`, and now the new exception is in `sys.exc_info()`, which causes Flask to [assert here](https://github.com/pallets/flask/blob/01081dbe6cdfa3fc43d8e1fff708d4ed95e1be7e/flask/app.py#L1515).

Searching git history for the introduced `exc=` in `FlaskParser`, I found it here: https://github.com/sloria/webargs/commit/6f8088c7c85c05d2891e81ee97d38f2ae801159d

Is there a reason for `exc=` to be passed? How can we fix this?

Python 3 seems to have changed something with `sys.exc_info()` behaviour since even after the `TypeError` caused by `json.dumps()`, `sys.exc_info()` still reports `HTTPException` while in Python 2 it returns `TypeError`.

### PR DESCRIPTION
**Pull request by frol**
Closes #122.

### CODE REVIEW

**Comment by frol** [comment]
OK, it seems that `exc` has some value, but maybe it can be put in a separate attribute?

**Comment by frol** [comment]
Using this patched version of webargs my tests are back all green on Python 2.x.

**Review by sloria — CHANGES_REQUESTED** [review]
I would like to see a regression test that reproduces the bug. I am not able to reproduce the error in the current test suite on Python 2 with Flask 0.11.1.

@frol Would you mind adding a regression test?

**Comment by frol** [comment]
I'll try.

**Comment by sloria** [comment]
Thanks so much!

**Comment by frol** [comment]
OK, in fact, it seems to be Flask-RESTful/Flask-RESTplus specific as they handle the error in a way that just throw all `e.data` into JSON dump:
- Flask-RESTful - https://github.com/flask-restful/flask-restful/blob/63cadac8043e2070a22b5ab34a2656b804ef620f/flask_restful/__init__.py#L311
- Flask-RESTplus - https://github.com/noirbizarre/flask-restplus/blob/c0b25877b1089e354086a4a25f2f7e01f267baac/flask_restplus/api.py#L572

Do you still think that `data` should contain `exc`? I can go and create issues on those projects instead of "fixing" this here.

**Comment by sloria** [comment]
Thanks for investigating @frol . I think your solution here is valid; `e.data` is meant to contain the data to be returned in JSON responses.

It would still be great to have a regression test for this.

**Comment by frol** [comment]
I have added the test.

**Review by sloria — APPROVED** [review]

**Pull request merged**
