### PR TITLE
Add DelimitedTuple to fields.__all__

### PR DESCRIPTION
**Pull request by lafrech**

### CODE REVIEW

**Review by sirosen — APPROVED** [review]
Good catch. This makes me want to do v8.1.0 fairly soon, since we now have a fix pending.

**Comment by lafrech** [comment]
Sure.

I created a milestone and added #667, #663 and #661. We may want to postpone the latter if it takes too much time.

**Comment by lafrech** [comment]
8.1.0 all clear except for #661. We don't have to wait for it. No rush to release either.

@sirosen I updated the CHANGELOG. You may release 8.1.0 if you want.

**Comment by sirosen** [comment]
I'll try to get to a release done today or tomorrow. Thanks for handling the changelog!

That reminds me: I want to be more consistent about keeping an up-to-date changelog with unreleased changes, as `marshmallow` does. I've been lax about it and will try to be better on that front.

**Comment by sirosen** [comment]
@lafrech, just to keep you in the loop, I just pushed out the 8.1.0 release. 🎊

**Comment by lafrech** [comment]
Thanks. It's frustrating repo watchers don't get notified about new tags.

**Pull request merged**
