### PR TITLE
fix DelimitedList return [''] when field value is empty string

### PR DESCRIPTION
**Pull request by TTWShell**

### CODE REVIEW

**Comment by TTWShell** [comment]
#623

**Comment by sirosen** [comment]
Sorry for the slow turnaround on this -- I've been away from webargs for a little. Just caught up, and thanks for contributing the fix! 😄 
The fix looks good and I can't think of any weird corner cases. I'm going merge it.

@lafrech, should I do a point release with this, 8.0.1?

**Comment by lafrech** [comment]
Yes, sorry about this. Saw it then forgot. Holidays. Thanks for the fix.

> @lafrech, should I do a point release with this, 8.0.1?

Absolutely.

Care to add @TTWShell to authors?

Thanks.

**Comment by lafrech** [comment]
NVM, I did the release.

**Pull request merged**
