### PR TITLE
Add note in docs for nested fields and locations

### PR DESCRIPTION
**Pull request by imhoffd**
re: https://github.com/sloria/webargs/issues/74

### CODE REVIEW

**Comment by sloria** [comment]
Don't worry about the test failure; it is unrelated to your changes.

**Comment by sloria** [comment]
As noted in https://github.com/sloria/webargs/issues/74#issuecomment-154743501, `Nested` fields aren't  exclusive to JSON request bodies. Perhaps it would be useful to document an example of a custom parser that handles nesting in query params?

**Comment by imhoffd** [comment]
Is this more of what you're thinking? The example I wrote up is a bit verbose, unfortunately.

**Comment by sloria** [comment]
Looking good. Indeed, the example is a bit complicated for a quickstart, but it's a useful example nonetheless.

I just added a few "Advanced" topics to the quickstart. I think the "Custom Parser" section falls under that category. Can you update with the `dev` branch and put Custom Parser in the Advanced section?

Also, it might help to add a docstring to the custom parser, with an example of the expected URL format.

**Comment by imhoffd** [comment]
Good call. How's it looking?

**Comment by sloria** [comment]
Looks great. Thanks!

**Pull request merged**
