### PR TITLE
Use type hints made available in Python 3.9 and 3.10.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**

### CODE REVIEW

**Comment by sirosen** [comment]
I've been really excited about replacing `typing.Union` with `|`. However, doing this will require py3.7+, since the future import wasn't introduced until 3.7.

I'm hesitant about merging this, at least until we've discussed 3.6 support. (Even though 3.6 reaches EOL soon, many people will be running it for a few more years.)

Thanks for getting us started on this. The PR might have to sit for a while, but the work is still very much appreciated and very useful.

**Comment by lafrech** [comment]
Actually marshmallow drops EOLed Python versions and I intended to drop 3.6 soonish in webargs too.

https://github.com/marshmallow-code/marshmallow/issues/1856
https://github.com/marshmallow-code/marshmallow/pull/1923
https://github.com/marshmallow-code/apispec/pull/727

Thanks for this contribution. Nice to move forward with new language features.

**Comment by lafrech** [comment]
@Isira-Seneviratne would you like to provide an equivalent PR for marshmallow once https://github.com/marshmallow-code/marshmallow/pull/1923 is merged?

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne would you like to provide an equivalent PR for marshmallow once [marshmallow-code/marshmallow#1923](https://github.com/marshmallow-code/marshmallow/pull/1923) is merged?

Sure.

UPDATE: I've made the PR here: https://github.com/marshmallow-code/marshmallow/pull/1926

**Comment by sirosen** [comment]
I've just applied a change here to resolve conflicts and get linting to pass. It's passing in CI, so I'm going to move ahead and merge this.

Thanks again for the contribution. 😄

**Comment by lafrech** [comment]
I was waiting for https://github.com/marshmallow-code/marshmallow/pull/1932 to be merged. But the reason it is not merged already is mostly questions I had, nothing blocking.

**Comment by sirosen** [comment]
I hadn't realized. I assume it's no big deal, but sorry all the same.
Before we release 8.1.0 of `webargs`, let's make sure we're comfortable with this in marshmallow too.

**Comment by lafrech** [comment]
No pb. Those questions mostly highlight my ignorance when it comes to typing. Worst case, the PR was incomplete or the commit comment is not perfectly exact. No big deal at all.

**Pull request merged**
