### PR TITLE
Add Sanic support: parser, test app, tests

### PR DESCRIPTION
**Pull request by dnikolayev**
We commonly use webargs + flask.
However, there was a requirement to build a project using Sanic.
To have the same style support with common practice Sanic support was added.
Please review.
@sloria, to enable Sanic support webtest-sanic package was released. The code of webtest-sanic is fully based on your library webtest-aiohttp and all creds saved.

### CODE REVIEW

**Comment by sloria** [comment]
Hi @dnikolayev . Thanks for your work on this!

In order to keep this library small and easy to maintain, we've stopped adding support for new frameworks, so I'm going to close this.

For now, I recommend adding webargs-sanic to https://github.com/sloria/webargs/wiki/Ecosystem . I'll forward people to that library when asked about sanic support.

Also, would it help if `CommonTestCase` were exposed in the PyPI package so you could import it in webargs-sanic?

**Comment by dnikolayev** [comment]
Ok, I see. I already started to update docs and check contributing policies to pass everything, LOL

As for the "CommonTestCase" - Well, I guess so.  
Could you please release it? Will it take much time?

**Comment by sloria** [comment]
@dnikolayev I'll try to make a new release with CommonTestCase after work today

**Comment by lafrech** [comment]
> In order to keep this library small and easy to maintain, we've stopped adding support for new frameworks

Maybe we ought to update `CONTRIBUTING.rst` to mention that.

**Comment by dnikolayev** [comment]
Thnx @sloria 
I will wait.
While you're preparing the shared version of test class - I used a copy of it here: https://github.com/EndurantDevs/webargs-sanic
Will change to shared version once you create it. Probably it will be the great idea to have it shared between the core project and versions for other frameworks.

Thanks again for your help!

**Comment by sloria** [comment]
@dnikolayev OK, 4.1.0 includes `webargs.testing.CommonTestCase`.

**Comment by sloria** [comment]
Also, I've updated CONTRIBUTING.rst. Good idea, @lafrech

**Comment by dnikolayev** [comment]
I removed a copy of common tests. `webargs.testing.CommonTestCase` is used in tests.
Also, I've extended tests locally, including testing files validation via Sanic's test client.
Package is released, you can always send people who needs integration with Sanic to [webargs-sanic](https://github.com/EndurantDevs/webargs-sanic)

@sloria, Thanks for your help!

**Pull request closed without merging**
