### PR TITLE
Added quartparser

### PR DESCRIPTION
**Pull request by esfoobar**
This is a parser that works with the Quart framework, for your review.

### CODE REVIEW

**Comment by esfoobar** [comment]
I need to write some tests, will commit again after I do.

**Comment by lafrech** [comment]
Thanks.

Please see https://github.com/marshmallow-code/webargs/issues/151#issuecomment-284408054.

If you release webargs-quart, please let us know so that we add it to the dedicated wiki page: https://github.com/marshmallow-code/webargs/wiki/Ecosystem.

**Comment by esfoobar** [comment]
Hi @lafrech,

Please check the [webargs-quart](https://github.com/esfoobar/webargs-quart) package so that you can publish in your wiki.

Let me know if you need anything else.

Cheers!

**Comment by lafrech** [comment]
Good.

For the package structure (file hierarchy, tests, CI, releases,...), you could take inspiration in the other equivalent frameworks plugins:

- https://github.com/sloria/webargs-starlette
- https://github.com/EndurantDevs/webargs-sanic
- https://github.com/tyler46/nameko-webargs

I added your plugin to the list: https://github.com/marshmallow-code/webargs/wiki/Ecosystem.

Thanks for sharing.

**Pull request closed without merging**
