### PR TITLE
Pyramid support

### PR DESCRIPTION
**Pull request by philtay**
Please let me know if you want to add Pyramid support and I'll complete the work.

### CODE REVIEW

**Comment by sloria** [comment]
+1. I have been meaning to add Pyramid support, so thanks for picking this up.

**Comment by philtay** [comment]
Have you an idea on why the Travis build continues to fail? I've added Pyramid as a dependency.

**Comment by sloria** [comment]
It was because the .travis.yml was not configured to install pyramid. I updated the file to install all the `dev-requirements.txt`, so syncing with `dev` should fix it.

**Comment by philtay** [comment]
Yep, I was sure to have added it.
Anyway, while I work on this I'd appreciate if you could merge or give a feedback on this https://github.com/sloria/marshmallow/pull/72
It's something I really need.
Tnx

**Pull request closed without merging**
